DROP DATABASE IF EXISTS `euro_lieutenantDB`;
CREATE DATABASE `euro_lieutenantDB`;
USE `euro_lieutenantDB`;

CREATE TABLE product (
  product_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  image TINYTEXT,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_products PRIMARY KEY(product_id)
);


CREATE TABLE user (
  user_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_user PRIMARY KEY(user_id)
);

CREATE TABLE contacts (
  contact_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_contacts PRIMARY KEY(contact_id)
);

ALTER TABLE products RENAME TO product;