INSERT INTO products (image, name, price, description)
VALUES
('https://image-us.samsung.com/SamsungUS/home/televisions-and-home-theater/tvs/03012019/Q70R_003_R-Perspective_Slate-Black_NS.jpg?$product-details-jpg', 'Samsung QN65Q70RAFXZA Flat 65-Inch QLED 4K Q70 Series Ultra HD Smart TV with HDR and Alexa Compatibility (2019 Model)', 2199.99, 'The Samsung 4K TV is a high-quality television that boasts stunning picture quality with vibrant colors and deep blacks. With a 4K resolution and advanced features such as HDR and UHD upscaling, it delivers a cinematic viewing experience. Its sleek design and slim bezels make it a stylish addition to any room, while its intuitive Smart TV platform allows for easy access to your favorite streaming services and apps'),
('https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1572122-847&recipeName=680', 'Greenworks 21-Inch 80V Cordless Lawn Mower', 569.00, 'The GreenWorks 12 Amp Corded Lawn Mower is a versatile and efficient tool for keeping your lawn looking neat and trim. With a powerful 12 Amp motor and a 20-inch cutting deck, this mower can handle even tough mowing jobs with ease. It features 7 adjustable cutting heights, allowing you to customize the height of your grass, and a durable steel frame for long-lasting use. The mower is also lightweight and easy to maneuver, with large wheels that provide excellent traction on uneven terrain.'),
('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gkKysxsUmB4VX1sD8RDMuwHaE8%26pid%3DApi&f=1&ipt=0cc7b1f211ed9f6b2d855a7d1872400299575a42405f9d5013a69811606baa26&ipo=images', 'Alienware Aurora R11 Gaming Desktop', 1499.99, 'The Alienware Aurora R11 Gaming Desktop is a high-performance gaming PC designed to provide a seamless and immersive gaming experience. It is equipped with powerful hardware, including a 10th Gen Intel Core i7-10700KF processor, NVIDIA GeForce RTX 3070 graphics card, and 16GB DDR4 RAM. The desktop also features a sleek and stylish design with customizable RGB lighting and a high-quality cooling system to prevent overheating during intense gaming sessions. With its top-of-the-line specifications and advanced features, the Alienware Aurora R11 is an excellent choice for serious gamers looking for the best possible gaming experience.'),
('https://www.justtires.com/content/dam/gas-com/images/tireImages/goodyear/primaryImage/Eagle_F1_Asymmetric_2_2182.jpg', 'Goodyear Eagle F1 Asymmetric 2 Tire', 280.00, 'The Goodyear Eagle F1 Asymmetric 2 is a high-performance tire designed for sporty driving enthusiasts. It features an asymmetric tread pattern that provides superior grip and handling on both wet and dry roads. The tires advanced construction includes a reinforced shoulder and sturdy sidewalls, which contribute to its responsive handling and high-speed stability. The Goodyear Eagle F1 Asymmetric 2 also boasts excellent braking capabilities, thanks to its specially formulated tread compound and unique grooves that evacuate water from under the tire.'),
('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Ftheproscloset-img%2FBRD12407_BJ_02.jpg&f=1&nofb=1&ipt=958e49989cceb854aa52e102a50001cd5918d7f0fb796a9382d4308f44654186&ipo=images', 'Specialized Roubaix Sport Road Bike', 3499.99, 'The Specialized Roubaix Sport Road Bike is a high-performance road bike designed for the serious cyclist. With its lightweight carbon frame and fork, it provides a smooth and responsive ride, perfect for tackling challenging terrain. It features Shimano 105 drivetrain components for precise and reliable shifting, and hydraulic disc brakes for confident stopping power in all conditions. The Roubaix Sport also comes equipped with a range of high-quality components, including a carbon seatpost, alloy handlebars, and a comfortable Body Geometry saddle, making it a great choice for long-distance rides and competitive events.'),
('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F0988%2F4598%2Fproducts%2Fguccimarmontbelt65_1.jpg%3Fv%3D1621239175&f=1&nofb=1&ipt=c81a81bfc9ca9b811eb5f75385414939339a912f31e1b455fd5b6b1aa8d255c3&ipo=images', 'GG Marmont Leather Belt', 490.00, 'The GG Marmont Leather Belt from Gucci is a luxury fashion accessory designed for those who appreciate style and quality. Made from smooth black leather, it features the signature double G buckle in an antique gold tone for a timeless look. This adjustable belt can be worn with a variety of outfits, making it a versatile addition to any wardrobe.'),
('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.servimg.com%2Fu%2Ff62%2F19%2F79%2F78%2F80%2Fscreen10.jpg&f=1&nofb=1&ipt=2b898dfccc7b2611b5e2e4db35cbba255e76545d23fbff5b79d9e93c5a4e5628&ipo=images', 'The Power Wheels Monster Jam Grave Digger', 100.99, 'The Power Wheels Monster Jam Grave Digger is a miniature replica of the famous monster truck, perfect for kids who love big trucks and big adventures. It features realistic graphics and styling, and can drive over hard surfaces, grass, and rough terrain with ease. With a maximum speed of 5 mph, its both safe and exciting for young drivers. The truck also has a sturdy steel frame and a high-back seat for added safety and comfort.'),
('https://youbentmywookie.com/wookie/uploads/2019/07/arcade1up-star-wars-cabinet-3.jpg', 'Arcade1Up Star Wars Arcade Cabinet', 760.00, 'The Arcade1Up Star Wars Arcade Cabinet is a gaming machine that features three classic Star Wars games: Star Wars, The Empire Strikes Back, and Return of the Jedi. It has a 17-inch color LCD screen, authentic artwork, and retro-style joysticks and buttons for an authentic arcade experience. The cabinet is decorated with iconic Star Wars characters and images, and the game is housed in a sturdy cabinet with adjustable riser. The Arcade1Up Star Wars Arcade Cabinet is perfect for fans of the classic Star Wars games who want to relive the excitement of the arcade.'),
('https://image-us.samsung.com/SamsungUS/home/home-appliances/washers/front-load/pd/wf45k6500av/10_Washer_FrontLoader_WF45K6500AV_L_Perspective_AddWash_Open_Low_Angle_Pedestal_Black111617.jpg?$product-details-jpg', 'Samsung WF45K6500AV Front Load Washer', 674.99, '
The Samsung WF45K6500AV is a high-end front load washer designed to deliver powerful and efficient cleaning. With a capacity of 4.5 cubic feet, this washer can easily handle large loads of laundry, making it ideal for families. It features Samsungs innovative AddWash door that allows you to easily add forgotten items even after the cycle has started. The washer also comes with Wi-Fi connectivity, allowing you to control and monitor it from your smartphone. The WF45K6500AV offers a variety of wash options and settings, including steam cleaning, which helps remove stains and deep cleans your clothes. Its sleek design and black stainless steel finish add a touch of elegance to any laundry room.'),
('https://i.ebayimg.com/images/g/gKcAAOSwFPRZxvJp/s-l1600.jpg', 'Libman Wonder Mop', 14.47, 'The Libman Wonder Mop is a popular cleaning tool designed to make mopping more efficient and effective. It features a machine-washable microfiber mop head that is highly absorbent and can clean tough dirt and grime from various surfaces. The Wonder Mop also has a power wringer to help you remove excess water and reduce drying time, while the long handle and swivel head make it easy to reach and clean hard-to-reach areas. This mop is a great choice for those who want a high-quality cleaning tool that can handle heavy-duty cleaning tasks.');


INSERT INTO user (username, password) VALUES
    ('John Doe', 'johndoe101');